freebsd_task:
  freebsd_instance:
    matrix:
      - image: freebsd-10-4-release-amd64
      - image: freebsd-11-2-release-amd64
      - image: freebsd-12-1-release-amd64
  install_script: pkg install -y dash bash zsh ksh93 mksh oksh pdksh
  prepare_script:
    - echo --force-color > ./.shellspec-local
    - ./shellspec --task fixture:stat:prepare
  script:
    - contrib/all.sh contrib/various_test.sh

gitbash_task:
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019
  env:
    PATH: $ProgramFiles\Git\bin;$PATH
  install_script:
    - git --version
  prepare_script:
    - bash -c "env | grep -E '^(LC_|LANG|CYGWIN|MSYS)'"
    - bash -c "mount"
    - bash -c "echo --force-color > ./.shellspec-local"
    - bash -c "./shellspec --task fixture:stat:prepare"
  script:
    - bash -c "contrib/all.sh contrib/various_test.sh"

msys_task:
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019
  env:
    PATH: C:\tools\msys64\usr\bin;$PATH
  install_script:
    - choco install -y --no-progress msys2
    - pacman.exe -Syu --noprogressbar --noconfirm
    - pacman.exe -S --noprogressbar --noconfirm dash bash busybox mksh
    - pacman.exe -Q
  prepare_script:
    - bash -c "env | grep -E '^(LC_|LANG|CYGWIN|MSYS)'"
    - bash -c "mount"
    - bash -c "echo --force-color > ./.shellspec-local"
    - bash -c "./shellspec --task fixture:stat:prepare"
  script:
    - bash -c "contrib/all.sh shellspec"

cygwin_task:
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019
  env:
    PATH: C:\tools\cygwin\bin;$PATH
  install_script:
    - choco install -y --no-progress cygwin cyg-get
    - cyg-get nc dash bash busybox mksh posh zsh
    - cygcheck -c
  prepare_script:
    - bash -c "env | grep -E '^(LC_|LANG|CYGWIN|MSYS)'"
    - bash -c "mount"
    - bash -c "echo --force-color > ./.shellspec-local"
    - bash -c "./shellspec --task fixture:stat:prepare"
    # I don't know why but tests using below files fail in cirrus ci environment.
    - bash -c "rm -f ./spec/fixture/stat/{readable,writable}"
  script:
    - bash -c 'contrib/all.sh shellspec'
