freebsd_task:
  freebsd_instance:
    matrix:
      - image: freebsd-10-4-release-amd64
      - image: freebsd-11-2-release-amd64
      - image: freebsd-12-0-release-amd64
  install_script: pkg install -y dash bash zsh ksh93 mksh oksh pdksh
  prepare_script:
    - ./shellspec --task fixture:stat:prepare
  script:
    - contrib/all.sh contrib/various_test.sh

gitbash_task:
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019
  env:
    PATH: $PATH;$ProgramFiles\Git\bin
  prepare_script:
    - bash -c './shellspec --task fixture:stat:prepare'
  script:
    - bash -c 'contrib/all.sh contrib/various_test.sh'

msys_task:
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019
  env:
    PATH: $PATH;C:\tools\msys64\usr\bin
  install_script:
    - choco install -y msys2
    - pacman.exe -Syu --noconfirm
    - pacman.exe -S --noconfirm dash bash mksh zsh
  prepare_script:
    - bash -c './shellspec --task fixture:stat:prepare'
  script:
    - bash -c 'contrib/all.sh contrib/various_test.sh'

cygwin_task:
  windows_container:
    image: cirrusci/windowsservercore:2019
    os_version: 2019
  env:
    PATH: $PATH;C:\tools\cygwin\bin
  install_script:
    - choco install -y cygwin cyg-get
    - cyg-get nc dash bash mksh posh zsh
  prepare_script:
    - bash -c './shellspec --task fixture:stat:prepare'
  script:
    - bash -c 'contrib/all.sh contrib/various_test.sh'

CirrusCI_task:
  depends_on:
    - freebsd
    - gitbash
    - msys
    - cygwin
  container:
    image: busybox
  done_script:
    - echo all ok
