language: sh
env:
  global:
    - HOMEBREW_NO_AUTO_UPDATE=1
addons:
  apt:
    update: true
  homebew:
    update: true
matrix:
  include:
    - os: linux
      dist: xenial
      env: PKG="dash bash zsh ksh mksh yash posh busybox"
    - os: osx
      osx_image: xcode10.2
      env: PKG="dash bash zsh ksh mksh yash"
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get install -y $PKG; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install $PKG; fi
before_script:
  - shellspec --task fixture:stat:prepare
script:
  - contrib/all.sh contrib/various_test.sh
