language: sh
env:
  global:
    - HOMEBREW_NO_AUTO_UPDATE=1
addons:
  apt:
    update: true
  homebew:
    update: true
matrix:
  include:
    - os: linux
      dist: precise # Ubuntu 12.04
      env: PKG="dash bash zsh ksh mksh yash posh busybox"
    - os: linux
      dist: trusty # Ubuntu 14.04
      env: PKG="dash bash zsh ksh mksh yash posh busybox"
    - os: linux
      dist: xenial # Ubuntu 16.04
      env: PKG="dash bash zsh ksh mksh yash posh busybox"
    - os: osx
      osx_image: xcode6.4 # macOS 10.10 Yosemite 2014-06
      env: PKG=""
    - os: osx
      osx_image: xcode8 # macOS 10.11 El Capitan 2015-06
      env: PKG=""
    - os: osx
      osx_image: xcode9.2 # macOS 10.12 Sierra 2016-06
      env: PKG=""
    - os: osx
      osx_image: xcode10.1 # macOS 10.13 High Sierra 2017-06
      env: PKG=""
    - os: osx
      osx_image: xcode10.2 # macOS 10.14 Mojave 2018-06
      env: PKG=""
    - os: osx
      osx_image: xcode10.2 # macOS 10.14 Mojave 2018-06
      env: PKG="dash bash zsh ksh mksh yash"
before_install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ] && [ "$PKG" ]; then sudo apt-get install -y $PKG; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$PKG" ]; then brew install $PKG; fi
before_script:
  - ./shellspec --task fixture:stat:prepare
script:
  - contrib/all.sh contrib/various_test.sh
