name: macOS Big Sur

on: [push, pull_request]

env:
  FORCE_COLOR: 1

jobs:
  macos-bigsur:
    runs-on: macos-11.0
    strategy:
      matrix:
        shells:
          - {shell: sh}
          - {shell: dash}
          - {shell: bash}
          - {shell: ksh}
          - {shell: zsh}
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - run: ${{ matrix.shells.shell }} ./shellspec --shell "${{ matrix.shells.shell }}" --task fixture:stat:prepare
      - run: SH="${{ matrix.shells.shell }}" contrib/various_test.sh
